site_name: "1С: Внедрение — Документация"
site_url: "https://andrzejabramov.github.io/integration_1c_unf/"

theme:
  name: material
  palette:
    primary: blue
    accent: orange
  features:
    - navigation.tabs
    - navigation.sections
    - search

nav:
  - 📋 Выводы: resume.md                    ← Пути ОТНОСИТЕЛЬНО папки docs/
  - 📘 1С:УНФ:
    - Интерфейс: 1c_unf/interface_unf.md
  - 📘 1С:КА:
    - Интерфейс: 1c_ka/interface_ka.md
  - 📁 Алгоритмы: 1c_algoritm/
  - 🖼️ Скриншоты:
    - УНФ: img/unf/
    - КА: img/ka/

markdown_extensions:
  - toc
  - tables
  - admonition
  - codehilite